<?php

namespace AppBundle\Repository;

/**
 * EncadrantExterneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncadrantExterneRepository extends \Doctrine\ORM\EntityRepository
{
}
