<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Semestre;

/**
 * EnseignementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySemestre(Semestre $semestre){
        return $this->createQueryBuilder('e')
            ->where('e.semestre = :semestre')
            ->setParameter('semestre', $semestre)
            ->getQuery()
            ->getResult();
    }
}
