<?php

namespace AppBundle\Repository;

/**
 * MembreJuryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreJuryRepository extends \Doctrine\ORM\EntityRepository
{
}
