<?php

namespace AppBundle\Repository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends \Doctrine\ORM\EntityRepository
{
    public function isLibelleExist($name)
    {
        if($this->createQueryBuilder('d')
            ->where('d.libelle = :name')
            ->setParameter('name', $name)
            ->getQuery()
            ->getResult()){
            return true;
        }else{
            return false;
        }
    }
    public function countModules()
    {
            return $this->createQueryBuilder('m')
                ->select('count(m)')
                ->getQuery()
                ->getSingleScalarResult();
    }

}
