<?php

namespace AppBundle\Repository;

/**
 * StageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOldStages()
    {
        $date=new \DateTime();
        return $this->createQueryBuilder('s')
            ->where('s.dateFin <= :now')
            ->setParameter('now', $date->format("Y-m-d"))
            ->getQuery()
            ->getResult();
    }

    public function getNewStages()
    {
        $date=new \DateTime();
        return $this->createQueryBuilder('s')
            ->where('s.dateFin >= :now')
            ->setParameter('now', $date->format("Y-m-d"))
            ->getQuery()
            ->getResult();
    }

    public function countStages()
    {
        return $this->createQueryBuilder('f')
            ->select('count(f)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
