# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory,teacher_provider, student_provider]
        teacher_provider:
            entity:
                class: AppBundle:Teacher
        student_provider:
            entity:
                class: AppBundle:Student
        in_memory:
            memory:
                users:
                    admin@ensak.com:
                        password: $2y$13$HV0QhMPEStxTpVbM6HzaJOV/xUqYsi7vq2T/g9uoHDcEQUoT2NQj.
                        roles: 'ROLE_ADMIN'
    role_hierarchy:
        ROLE_TEACHER:     ROLE_USER
        ROLE_STUDENT:       ROLE_USER
        ROLE_ADMIN:       ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|files)/
            security: false

        main:
            anonymous: ~
            provider: chain_provider
            remember_me:
                secret:   '%secret%'
            logout:
                            path:   /logout
                            target: /
            form_login:
                login_path: /login
                check_path: /login
                default_target_path: /
                always_use_default_target_path: true
                failure_path: /login

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
            - { path: ^/teacher, roles: ROLE_TEACHER }
            - { path: ^/student, roles: ROLE_STUDENT }
            - { path: ^/admin, roles: ROLE_ADMIN }